"""ARAVINDHA — project source dump generator.

Walks the repository and writes ONE text file (PROJECT_FULL_SOURCE.md) that
contains the complete source tree in reading order: project stats, file
inventory, then every source file's full contents under a fenced block.

Skips generated/derived artifacts (node_modules, .git, .freebuff runtime files,
DEM/API caches, lockfiles, compiled ONNX/wasm binaries, pycache) so the dump
stays a true representation of the project's own code.
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "PROJECT_FULL_SOURCE.md")

# Directories never included (derived, third-party, or runtime state).
SKIP_DIRS = {
    "node_modules", ".git", ".freebuff", "__pycache__", "dist", "build",
    ".vite", ".cache", "ort", ".idea", ".vscode", "coverage",
}
# Exact file names skipped (generated/binary/large-ish lockfiles).
SKIP_FILES = {
    "package-lock.json", "server/package-lock.json", "yarn.lock",
    ".DS_Store", "project-id",
}
# Path fragments skipped anywhere they appear.
SKIP_FRAGMENTS = (
    "ml-service/data/",      # DEM/rainfall API caches + build reports
    "public/model.onnx",     # binary model
    "public/ort/",           # onnxruntime wasm binaries
)
# Text extensions that get dumped in full.
KEEP_EXT = {
    ".js", ".mjs", ".cjs", ".ts", ".jsx", ".tsx", ".css", ".html", ".json",
    ".py", ".sh", ".bat", ".ps1", ".sql", ".yml", ".yaml", ".toml", ".md",
    ".txt", ".env", ".gitignore", ".freebuff", ".onnx",
}
MAX_BYTES = 400_000  # never dump a single file larger than this


def is_text(path):
    try:
        with open(path, "rb") as fh:
            chunk = fh.read(4096)
        if b"\x00" in chunk:
            return False
        chunk.decode("utf-8")
        return True
    except Exception:
        return False


def collect():
    files = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for name in filenames:
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, ROOT).replace("\\", "/")
            if name in SKIP_FILES or any(frag in rel for frag in SKIP_FRAGMENTS):
                continue
            ext = os.path.splitext(name)[1].lower()
            if ext not in KEEP_EXT and name not in ("Dockerfile", "Procfile"):
                continue
            if os.path.getsize(full) > MAX_BYTES:
                continue
            if not is_text(full):
                continue
            files.append((rel, full))
    files.sort()
    return files


def main():
    files = collect()
    total_lines = 0
    counts = {}
    for rel, full in files:
        try:
            with open(full, encoding="utf-8", errors="replace") as fh:
                n = sum(1 for _ in fh)
        except Exception:
            n = 0
        counts[rel] = n
        total_lines += n

    out = []
    out.append("# ARAVINDHA — Complete Project Source\n")
    out.append("_Auto-generated by `scripts/make_project_dump.py` — every source file "
               "of the project, in full, in reading order._\n")
    out.append(f"- Files: **{len(files)}**")
    out.append(f"- Source lines: **{total_lines:,}**")
    out.append("- Excluded (generated/third-party/runtime): `node_modules/`, `.git/`, "
               "`.freebuff/`, `ml-service/data/.cache/`, `public/ort/`, "
               "`public/model.onnx`, `*lock.json`, `__pycache__/`\n")

    out.append("## 1. File inventory\n")
    out.append("```")
    for rel, _ in files:
        out.append(f"{counts[rel]:>6}  {rel}")
    out.append("```\n")

    out.append("## 2. Directory tree\n")
    out.append("```")
    tree = {}
    for rel, _ in files:
        parts = rel.split("/")
        node = tree
        for p in parts[:-1]:
            node = node.setdefault(p, {})
        node.setdefault("__files__", []).append(parts[-1])

    def render(node, prefix=""):
        dirs = sorted(k for k in node if k != "__files__")
        for d in dirs:
            out.append(f"{prefix}{d}/")
            render(node[d], prefix + "    ")
        for f in sorted(node.get("__files__", [])):
            out.append(f"{prefix}{f}")

    render(tree)
    out.append("```\n")

    out.append("## 3. Full source\n")
    for rel, full in files:
        out.append(f"### `{rel}`  ({counts[rel]} lines)\n")
        out.append("```" + lang_for(rel))
        try:
            with open(full, encoding="utf-8", errors="replace") as fh:
                out.append(fh.read().rstrip("\n"))
        except Exception as exc:  # pragma: no cover
            out.append(f"<unreadable: {exc}>")
        out.append("```\n")

    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out))
        fh.write("\n")

    size = os.path.getsize(OUT)
    print(f"WROTE {OUT}")
    print(f"  files={len(files)} lines={total_lines:,} size={size/1024:.0f} KB")
    return 0


LANG = {
    ".js": "javascript", ".mjs": "javascript", ".cjs": "javascript",
    ".ts": "typescript", ".css": "css", ".html": "html", ".json": "json",
    ".py": "python", ".sh": "bash", ".bat": "bat", ".sql": "sql",
    ".yml": "yaml", ".yaml": "yaml", ".md": "markdown", ".toml": "toml",
}


def lang_for(rel):
    return LANG.get(os.path.splitext(rel)[1].lower(), "text")


if __name__ == "__main__":
    sys.exit(main())
